### ISSUE TITLE
Install fails when dependencies are not already present

### ISSUE THREAD

**Issue by danielunderwood** [lehinevych/MediaWikiAPI#10]
The `from mediawikiapi import __version__` causes all of the imports in `__init__.py` to trigger, so `setup.py` can't be used by itself to install dependencies. I don't mind submitting a PR to change this if there's a preferred direction to go. The version could be removed from `__init__.py` or the other imports could be conditional on if the setup is being run.

**Comment by lehinevych** [comment]
Hi @danielunderwood 

Thanks for submitting #11 and #12. I figured out what's going on with tests and fixed them. Now your PRs have passed all checks successfully and are merged in master.
