### ISSUE TITLE
Please remove sphinx from install_requires  in setup.py

### ISSUE THREAD

**Issue by PaleNeutron** [lehinevych/MediaWikiAPI#29]
Sphinx is not a required lib for users who only want to use this lib instead of build/test it.

When people grab this package from pypi, they have to install the unnecessary sphinx!

According to https://setuptools.readthedocs.io/en/latest/setuptools.html#new-and-changed-setup-keywords, libs for docs and tests should be placed into `tests_require` instead of `install_requires`.

**Comment by lehinevych** [comment]
Yeah, you're right. Thanks. I'll fix it asap.

**Comment by lehinevych** [comment]
Fixed in version 1.1.4 by PR #31
