### ISSUE TITLE
Error installing 1.1.4 or updating from 1.1.3 to 1.1.4

### ISSUE THREAD

**Issue by DavidRayner** [lehinevych/MediaWikiAPI#33]
Error from pip when running: `pip install mediawikiapi==1.1.4` or `pip install mediawikiapi --upgrade`
```
    ERROR: Command errored out with exit status 1:
     command: /home/dev/miniconda3/envs/hub/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-lee8c8xs/mediawikiapi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-lee8c8xs/mediawikiapi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-lee8c8xs/mediawikiapi/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-lee8c8xs/mediawikiapi/setup.py", line 29, in <module>
        for line in local_file('requirements-test.txt').readlines()
      File "/tmp/pip-install-lee8c8xs/mediawikiapi/setup.py", line 17, in local_file
        os.path.join(os.path.dirname(__file__), file), 'r', 'utf-8'
      File "/home/dev/miniconda3/envs/hub/lib/python3.5/codecs.py", line 895, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-lee8c8xs/mediawikiapi/requirements-test.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by Javain** [comment]
getting the same one as well

>  ERROR: Command errored out with exit status 1:
     command: 'c:\users\habáin\appdata\local\programs\python\python37-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\HABIN~1\\AppData\\Local\\Temp\\pip-install-6h3any47\\mediawikiapi\\setup.py'"'"'; __file__='"'"'C:\\Users\\HABIN~1\\AppData\\Local\\Temp\\pip-install-6h3any47\\mediawikiapi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\HABIN~1\AppData\Local\Temp\pip-install-6h3any47\mediawikiapi\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\HABIN~1\AppData\Local\Temp\pip-install-6h3any47\mediawikiapi\setup.py", line 29, in <module>
        for line in local_file('requirements-test.txt').readlines()
      File "C:\Users\HABIN~1\AppData\Local\Temp\pip-install-6h3any47\mediawikiapi\setup.py", line 17, in local_file
        os.path.join(os.path.dirname(__file__), file), 'r', 'utf-8'
      File "c:\users\habáin\appdata\local\programs\python\python37-32\lib\codecs.py", line 904, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\HABIN~1\\AppData\\Local\\Temp\\pip-install-6h3any47\\mediawikiapi\\requirements-test.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by lehinevych** [comment]
Hi @DavidRayner and @Javain. 
Thanks a lot for reporting an issue. 

I fixed `setup.py` and release a new version 1.1.4.1. 
Please test if it works for you.

**Comment by DavidRayner** [comment]
All good now thanks :)  
`Successfully installed mediawikiapi-1.1.4.1`
