### ISSUE TITLE
Failed pip installation on Windows system

### ISSUE THREAD

**Issue by federicotorrielli** [lehinevych/MediaWikiAPI#40]
Currently, it's impossibile to install mediawikiapi from pip to any Windows system.
The module asks for pypandoc even if it's not required, as the following photo states:

![immagine](https://user-images.githubusercontent.com/31370059/97716879-71cb6780-1ac4-11eb-9ef3-b816394c0948.png)

But if we install pypandoc manually the error just changes to a similar one:

![immagine](https://user-images.githubusercontent.com/31370059/97716989-90c9f980-1ac4-11eb-950b-c59103f2c659.png)

Thanks in advance.

**Comment by lehinevych** [comment]
Hi Frederico, 

Thanks for creating the issue. I've addressed it in PR #42 . I'll release a new minor version within two days.

**Comment by federicotorrielli** [comment]
Nice, thanks.

**Comment by lehinevych** [comment]
@federicotorrielli the new version was released, could you please check if it works on Windows now?

**Comment by federicotorrielli** [comment]
It works very well now. I don't usually use Windows because I'm a big Linux fan but unfortunately I had to be away from home and control a windows server so.. Now everything it's ok!
