### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by TheBugYouCantFix** [lehinevych/MediaWikiAPI#46]
Here's a copypasta of the error:
`mediawikiapi.exceptions.MediaWikiAPIException: An unknown error occured: "Search request is longer than the maximum allowed length. (399 > 300)". Please report it on GitHub!`

**Comment by lehinevych** [comment]
Hi @TheBugYouCantFix 

I'm investigating the issue

**Comment by lehinevych** [comment]
@TheBugYouCantFix  the root cause of the issue is that search string length exceeded 300 characters. 

According to https://en.wikipedia.org/wiki/Help:Searching "The maximum search string is 300 characters long"

Could you provide the example which caused this issue?
