### ISSUE TITLE
Use black for consistency?

### ISSUE THREAD

**Issue by dpriskorn** [lehinevych/MediaWikiAPI#57]
I really like it and it plays well with mypy 😀

**Comment by lehinevych** [comment]
Hi @dpriskorn, 

Thanks and +1.  I've added the black formatting, typing and mypy checks in this [PR](https://github.com/lehinevych/MediaWikiAPI/pull/56)

Will improve it in the following CRs with refactoring to support async.

**Comment by lehinevych** [comment]
I've merged the PR. Closing the issue for now. Will be happy to hear your feedback.
