### ISSUE TITLE
Documentation should specify MediaWiki version

### ISSUE THREAD

**Issue by Idran** [lehinevych/MediaWikiAPI#61]
Since this library uses the TextExtracts API to retrieve page text and is meant to allow access to MediaWiki installations outside Wikipedia itself, it should be documented that full functionality is only available on MediaWiki version 1.34 or higher. (Specifically, the content, infobox, parent_id, revision_id, and summary calls in Page all don't function on the 1.33 install I tried this on.)

**Comment by lehinevych** [comment]
Thanks @Idran for reporting, I've update documentation to highlight that some functionality is available  on MediaWiki version 1.34 or higher.
